services:

  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abhay
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  service-registry:
    build:
      context: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - service-registry

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - service-registry

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - service-registry


  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - service-registry


  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - service-registry
      - rabbitmq

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - service-registry

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8090:8090"
    depends_on:
      - service-registry
      - rabbitmq

volumes:
  postgres-data:
