server:
  port: 8765

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: abhay
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000

  cloud:
    openfeign:
      circuitbreaker:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    hostname: order-service

logging:
  level:
    root: INFO
    com.example.order: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG